[build-system]
requires = [
    "setuptools>=61.0",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "verl"
dynamic = ["version"]
description = "veRL: Volcano Engine Reinforcement Learning for LLM"
license = {file = "LICENSE"}
readme = {file = "README.md", content-type = "text/markdown"}
requires-python = ">=3.8"

authors = [
  { name = "Bytedance - Seed - MLSys", email = "zhangchi.usc1992@bytedance.com" },
  { name = "Bytedance - Seed - MLSys", email = "gmsheng@connect.hku.hk" },
]

dependencies = [
    "accelerate",
    "codetiming",
    "datasets",
    "dill",
    "hydra-core",
    "numpy",
    "pybind11",
    "ray",
    "tensordict",
    "transformers<4.48",
    "vllm<=0.6.3",
    "flash-attn",
    "retry",
    "wandb"

]

[project.optional-dependencies]
test = [
  "pytest", "yapf"
]

[project.urls]
Homepage = "https://github.com/volcengine/verl"

[tool.setuptools]
include-package-data = true

[tool.setuptools.dynamic]
version = {file = "src/verl/version/version"}

[tool.setuptools.package-dir]
"" = "src"

[tool.setuptools.package-data]
verl = [
  "version/*",
  "trainer/config/*.yaml"
]